import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head';
import Layout from  '@/components/layout';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] })


export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title> KiloWhat </title>
      </Head>
      <main className={styles.main}>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </main>
    </>
  )
}
